### ISSUE TITLE
Sample JSONData Element 

### ISSUE THREAD

**Issue by whatnick** [FraunhoferIOSB/frost-sensorthings-datasource#446]
Provide sample for creating a datasource in Grafana JSONData pattern
```yaml
- name: NOAA SensorThings
  type: iosb-sensorthings-datasource
  jsonData:
    baseUrl: https://labs.waterdata.usgs.gov/sta/v1.1/
```
