### ISSUE TITLE
Grafana 8 compatibility

### ISSUE THREAD

**Issue by BWibo** [FraunhoferIOSB/frost-sensorthings-datasource#6]
Hey there, 

up front, thx for your great work, I'm using you SensorThingsAPI plugin a lot and really like it.
I just learned that the Linksmart repo is continued here. This is a repost of  linksmart/grafana-sensorthings-datasource#56.

I just updated my Grafana to `v8.1.1` and found the the datasource is apparently having some problems 
with Grafana version `>v8`.

Here is a reproducible example using Docker:

Create a folder with a copy from the `docker-compose.yml` listed below and run `docker-compose up` from the folder:

```yml
version: '3'

# Volumes ---------------------------------------------------------------------
volumes:
  grafana_data:
    # external: true
  grafana_config:
    # external: true

services:
# Grafana -------------------------------------------------------------------
  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", 'bash', '-c', 'wget -S "http://127.0.0.1:3000/api/health" |& grep "200 OK"']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:3000"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,
        grafana-worldmap-panel,marcusolsson-json-datasource
        ,https://github.com/linksmart/grafana-sensorthings-datasource/archive/refs/tags/v1.4.0.zip;linksmart-sensorthings-datasource"
      # Allow unsigned plugins
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "linksmart-sensorthings-datasource"
      # Admin user
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
```

As shown in the log, Grafana is setting up the plugin and starting with no error.

When I add a Datasource using the plugin, everything seems fine aswell. I get the "Datasrouce is working" notification.
Finally, when I want to use the Datasource in a Dashboard, nothing is happening and the Browser log shows this:

![err](https://user-images.githubusercontent.com/7643434/129013466-785d82cb-58d0-45aa-8b27-136ffe902133.png)

**Comment by rhzg** [comment]
thanks @BWibo for reposting this issue to the new "home" of the plugin. We are currently getting ourselfs familiar with the plugin, so we need to ask for a little patience before we are able to give you a good answer to your issue. The issue might have already been fixed with version 1.4.0, which is available in this repository, but has not been published to Grafana because of a open signing issue.

**Comment by BWibo** [comment]
Hey there, I just tried the code from this repo but I get the same error as reported above.
You can use this `docker-compose.yml` file to test the latested state of `master` of this repo:

```yml
version: '3'

# Volumes ---------------------------------------------------------------------
volumes:
  grafana_data:
    # external: true
  grafana_config:
    # external: true

services:
# Grafana -------------------------------------------------------------------
  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    ports:
      - 3000:3000/tcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", 'bash', '-c', 'wget -S "http://127.0.0.1:3000/api/health" |& grep "200 OK"']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:3000"
      # GF_INSTALL_PLUGINS: "https://github.com/linksmart/grafana-sensorthings-datasource/archive/master.zip;linksmart-sensorthings-datasourceeee"
      GF_INSTALL_PLUGINS: "https://github.com/FraunhoferIOSB/frost-sensorthings-datasource/archive/refs/heads/master.zip;forst-sensorthings-datasource"
      # Allow unsigned plugins
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "linksmart-sensorthings-datasource"
      # Admin user
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
```

The logging will look a little strange, because `dist/plugin.json` has not been updated jet.
